# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'WeatherAppICT' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherAppICT
	pod 'Alamofire', '~>5.0.0-rc.3'
	pod 'SwiftyJSON'

end
